# Generated by Django 4.2.1 on 2023-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eq_photo', verbose_name='이미지'),
        ),
    ]
