# Generated by Django 4.2.2 on 2023-06-21 17:25

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
