# Generated by Django 4.2.2 on 2023-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
