# Generated by Django 4.2.1 on 2023-05-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upperbody', '0003_post_photo_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
    ]
