# Generated by Django 4.2.1 on 2023-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowerbody', '0003_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='low_photo', verbose_name='이미지'),
        ),
    ]
